###############################################################################
# SPECtools98 
#   Version 0.3
#   This makefile should NOT be changed other than to customize for a 
#   particular benchmark.  Users may overide variables by placing them
#   in the Makefile.spec file.  Or by using the "runspec" program to 
#   build the Makefile.spec file for them.

###############################################################################
#	BENCHMARK	-- standard definitions for this benchmark

# Give pertinant information for this benchmark
NUMBER    = 165
NAME      = ijpeg
EXEBASE   = ijpeg
OFILES    = libpbm1 libpbm2 libpbm3 libpbm4 libpbm5 libpgm1 libpgm2 libppm1 libppm2 libppm3 libppm4 libppm5 spec_image spec_jmemdst spec_jmemsrc spec_main rdppm wrppm rdgif wrgif rdtarga wrtarga rdbmp wrbmp jcapi jcparam jdatadst jcmaster jcmarker jcmainct jcprepct jccoefct jccolor jcsample jchuff jcdctmgr jfdctfst jfdctflt jfdctint jdapi jdatasrc jdmaster jdmarker jdmainct jdcoefct jdpostct jddctmgr jidctfst jidctflt jidctint jidctred jdhuff jdsample jdcolor jquant1 jquant2 jdmerge jcomapi jutils jerror jmemmgr jmemnobs 

# Include standard template for this suite
-include ../../../Makefile.defaults
-include ../../Makefile.defaults
-include ../Makefile.defaults

# Allow user to override settings
include Makefile.spec

nomakefiles:
	@echo "*** Whoops!  I didn't find a Makefile.defaults file."
	@echo "*** You distribution is probably corrupt."
	@echo
